### PR TITLE
Feature/tr 33/rtl bottom action bar

### PR DESCRIPTION
**Pull request by lecosson**
**Related to:** https://oat-sa.atlassian.net/browse/TR-33

**Changes:**
- fixes for bottom tool bar for RTL languages

**How to check:**
- run delivery with enabled RTL language
- ensure elements placed properly

**Notes:**
- changes moved from [another PR](https://github.com/oat-sa/tao-test-runner-qti-fe/pull/404) to change magnitude from `fix` to `feature` 

**Another PR requires this one:**
 - [ ] https://github.com/oat-sa/extension-tao-testqti/pull/2037

### CODE REVIEW

**Review by marpesia — APPROVED** [review]
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x]  Commits messages are meaningful
- [x]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — CHANGES_REQUESTED** [review]
Mostly good, but I found issues with the "hide review" and the "end test" icons which should also be reverted.
image
image

image

Could you also check other navigation buttons, like the Next section button?

**Review by jsconan — COMMENTED** [review]
It looks better.

Just one little thing about the menus panel that is not aligned with the button trigger
RTL: image
LTR: image


**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

**Review by jsconan — APPROVED** [review]
looks good

**Pull request merged**
