### PR TITLE
Feature/nex 2170 enable scrollable passages

### PR DESCRIPTION
**Pull request by mike-ionut-mihai-sandu-tao**
Related to: https://oat-sa.atlassian.net/browse/NEX-2170
Rely to: https://github.com/oat-sa/extension-tao-itemqti/pull/1570

How to test:
  check `config/taoTests/test_runner_plugin_registry.conf.php` 
```
   'taoQtiTest/runner/plugins/content/itemScrolling/itemScrolling' => array(
            'id' => 'itemScrolling',
            'module' => 'taoQtiTest/runner/plugins/content/itemScrolling/itemScrolling',
            'bundle' => 'taoQtiTest/loader/testPlugins.min',
            'position' => null,
            'name' => 'Enable effect from enable/disable scrolling option',
            'description' => 'Add behavior from enable/disable scrolling option',
            'category' => 'content',
            'active' => true,
            'tags' => array(
            )
        ),
```
- go to Item authoring tool
- Select or add textblock
- In properties column activate enable scroll checkbox and set some option.
- Run test preview and if content in text block is bigger then page height there should appear scroll

Also need:
- [ ] Unit tests

### CODE REVIEW

**Comment by OlegBelanovich** [comment]
Related to: https://oat-sa.atlassian.net/browse/NEX-2170
Rely to: https://github.com/oat-sa/extension-tao-itemqti/pull/1570

How to test:
  check `config/taoTests/test_runner_plugin_registry.conf.php` 
```
   'taoQtiTest/runner/plugins/content/itemScrolling/itemScrolling' => array(
            'id' => 'itemScrolling',
            'module' => 'taoQtiTest/runner/plugins/content/itemScrolling/itemScrolling',
            'bundle' => 'taoQtiTest/loader/testPlugins.min',
            'position' => null,
            'name' => 'Enable effect from enable/disable scrolling option',
            'description' => 'Add behavior from enable/disable scrolling option',
            'category' => 'content',
            'active' => true,
            'tags' => array(
            )
        ),
```
- go to Item authoring tool
- Select or add textblock
- In properties column activate enable scroll checkbox and set some option.
- Run test preview and if content in text block is bigger then page height there should appear scroll

Also need:
- [ ] Unit tests

**Comment by habemuscode** [comment]
Added a bump version and resolve conflicts

**Review by habemuscode — APPROVED** [review]
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

**Review by bziondik — APPROVED** [review]
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Comment by habemuscode** [comment]
Changed class from `text-block-wrap` to `custom-text-box`

**Pull request merged**
